In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [8]:
data = pd.read_csv("movies_metadata.csv")
data

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [9]:
data.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [10]:
data.isnull().mean()/100

adult                    0.000000e+00
belongs_to_collection    9.011569e-03
budget                   0.000000e+00
genres                   0.000000e+00
homepage                 8.288391e-03
id                       0.000000e+00
imdb_id                  3.739058e-06
original_language        2.419390e-06
original_title           0.000000e+00
overview                 2.098271e-04
popularity               1.099723e-06
poster_path              8.489861e-05
production_companies     6.598337e-07
production_countries     6.598337e-07
release_date             1.913518e-05
revenue                  1.319667e-06
runtime                  5.784542e-05
spoken_languages         1.319667e-06
status                   1.913518e-05
tagline                  5.510491e-03
title                    1.319667e-06
video                    1.319667e-06
vote_average             1.319667e-06
vote_count               1.319667e-06
dtype: float64

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [12]:
data= data.drop_duplicates().reset_index(drop= True)

In [13]:
data = data[[
    'title',
    'overview',
    'tagline',
    'genres',
    'vote_average',
    'popularity'
]]

In [14]:
data

,title,overview,tagline,genres,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",NaN,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,"[{'id': 35, 'name': 'Comedy'}]",5.7,8.387519
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,Rising and falling between a man and woman,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",4.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,NaN,"[{'id': 18, 'name': 'Drama'}]",9.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...",A deadly game of wits.,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",3.8,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",NaN,[],0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,NaN,[],0.0,0.163015

In [15]:
data.isnull().sum()

title               6
overview          954
tagline         25045
genres              0
vote_average        6
popularity          5
dtype: int64

In [16]:
data = data.dropna(subset=['title'])

In [17]:
data['overview'] = data['overview'].fillna('')

In [18]:
data.iloc[0]['genres']
import ast

In [19]:
data["genres"]=data["genres"].apply(lambda x :" ".join([i["name"] for i in ast.literal_eval(x)]))

In [20]:
data['tagline'] = data['tagline'].fillna(" ")

In [21]:
data

,title,overview,tagline,genres,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",,Animation Comedy Family,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,Adventure Fantasy Family,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,Romance Comedy,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,Comedy Drama Romance,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Comedy,5.7,8.387519
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,Rising and falling between a man and woman,Drama Family,4.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,,Drama,9.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...",A deadly game of wits.,Action Drama Thriller,3.8,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",,,0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,,,0.0,0.163015

In [22]:
data.isnull().sum()

title           0
overview        0
tagline         0
genres          0
vote_average    0
popularity      0
dtype: int64

In [23]:
data['tags'] = data['overview'] + "" + data['tagline'] + "" + data['genres']

In [24]:
data

,title,overview,tagline,genres,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",,Animation Comedy Family,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,Adventure Fantasy Family,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,Romance Comedy,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,Comedy Drama Romance,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Comedy,5.7,8.387519,Just when George Banks has recovered from his ...
...,...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,Rising and falling between a man and woman,Drama Family,4.0,0.072051,Rising and falling between a man and woman.Ris...
45449,Century of Birthing,An artist struggles to finish his work while a...,,Drama,9.0,0.178241,An artist struggles to finish his work while a...
45450,Betrayal,"When one of her hits goes wrong, a professiona...",A deadly game of wits.,Action Drama Thriller,3.8,0.903007,"When one of her hits goes wrong, a professiona..."
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",,,0.0,0.003503,"In a small town live two brothers, one a minis..."
45452,Queerama,50 years after decriminalisation of homosexual...,,,0.0,0.163015,50 years after decriminalisation of homosexual...

In [25]:
data["tags"][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.Roll the dice and unleash the excitement!Adventure Fantasy Family"

In [26]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [27]:
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/madhavbassi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/madhavbassi/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [28]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [29]:
def preprocess_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z\s]','',text)
    words = text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

In [30]:
data["tags"] = data["tags"].apply(preprocess_text)

In [31]:
data["tags"][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creaturesroll dice unleash excitementadventure fantasy family'

In [32]:
preprocess_text(data["tags"][1])

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creaturesroll dice unleash excitementadventure fantasy family'

In [34]:
data = data.reset_index(drop = True)

In [37]:
indices = pd.Series(data.index, index = data['title']).drop_duplicates()

In [40]:
print(indices)

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [42]:

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')
tfidf_matrix = tfidf.fit_transform(data['tags'])
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1467856 stored elements and shape (45447, 50000)>

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

In [46]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return data['title'].iloc[similar_idx]

In [47]:
recommend('Avatar',5)

26547                  Avatar 2
13883      The Inhabited Island
43983       Nightmare City 2035
20372                    Désiré
28403    France société anonyme
Name: title, dtype: object

In [49]:

import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))
data.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))

In [51]:
recommend('Toy Story')

2996                          Toy Story 2
15344                         Toy Story 3
24512                           Small Fry
28972                     Superstar Goofy
17184                           Group Sex
11396              For Your Consideration
1071                Rebel Without a Cause
485                                Malice
1931                            Condorman
43408    Andy Kaufman Plays Carnegie Hall
Name: title, dtype: object